[package]
name = "prussia_rt"
version = "0.4.2"
license = "MIT OR Apache-2.0"
authors = ["Dan Ravensloft <dan.ravensloft@gmail.com>"]
edition = "2018"

[dependencies]
bitflags = "1.0.4"
prussia_debug = { version = "0.1.0", path = "../prussia_debug" }
r0 = "0.2.2"
